# Generated by Django 6.0.7 on 2026-07-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(upload_to='profile/')),
                ('about', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=100)),
                ('github', models.URLField()),
                ('linkedin', models.URLField()),
                ('resume', models.FileField(upload_to='resume/')),
            ],
        ),
    ]
