# Generated by Django 6.0.7 on 2026-07-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='hero_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
