# Generated by Django 6.0.7 on 2026-08-03 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0004_portfolio_hero_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_email', models.EmailField(max_length=254, unique=True)),
                ('emp_phone', models.CharField(max_length=15)),
                ('emp_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emp_address', models.TextField()),
            ],
        ),
    ]
